
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                   '$status $body_bytes_sent "$http_referer" '
    #                   '"$http_user_agent" "$http_x_forwarded_for"';

    log_format main '$remote_addr - [$time_local] '
                '"$host$request_uri" $status $body_bytes_sent - "$request_method" '
                '"$http_user_agent" - "$http_referrer"' ;



    access_log /var/log/nginx/access.log main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    # load server that redirects http to https
    include /etc/nginx/includes/http_to_https.conf;

    # load manual configurations 
    # (deactivated for now, as we are using templates instead)
    # include /etc/nginx/conf.d/*.conf;

    # load confs post-processed from templates
    include /etc/nginx/sites-enabled/*.conf;
}
