# generic configuration for ssl, to be included in each ssl server block
listen 443 ssl;
#ssl_certificate /etc/letsencrypt/live/tre-cert/fullchain.pem;  
#ssl_certificate_key /etc/letsencrypt/live/tre-cert/privkey.pem;
ssl_certificate /etc/letsencrypt/live/adele-certs/fullchain.pem;  
ssl_certificate_key /etc/letsencrypt/live/adele-certs/privkey.pem;

location /.well-known/acme-challenge/ {
    root /var/www/certbot;
}