server {
  server_name backoffice.adele.inesc-id.pt;
  include includes/ssl.conf;

  location / {
    proxy_pass http://adele-backoffice-frontend:80;
  }
}

server {
  server_name backoffice-api.adele.inesc-id.pt;
  include includes/ssl.conf;

  location / {
    proxy_pass http://adele-backoffice-backend:8081;
  }
}

